package net.teamaof.skylorebosses.bosses.amanita;

import java.util.Map;
import net.teamaof.skylorebosses.core.fx.ModelLocators;

/** GENERATED by bosses/amanita/tools/export_to_mod.py from the Blockbench specs. Rest-pose locators in model pixels. */
public final class AmanitaLocators {
    private AmanitaLocators() {}

    public static void register() {
        ModelLocators.register("amanita", Map.ofEntries(Map.entry("core", new float[]{0.00f, 33.20f, -3.20f}), Map.entry("head", new float[]{0.00f, 42.80f, -2.60f}), Map.entry("gills", new float[]{0.00f, 43.90f, 0.00f}), Map.entry("cap", new float[]{0.00f, 48.40f, 0.00f}), Map.entry("hand_l", new float[]{-6.70f, 14.00f, -1.00f}), Map.entry("hand_r", new float[]{6.70f, 14.00f, -1.00f}), Map.entry("feet", new float[]{0.00f, 0.00f, 0.00f})));
        ModelLocators.register("lamp_eater", Map.ofEntries(Map.entry("mouth", new float[]{0.00f, 3.40f, -12.50f}), Map.entry("feet", new float[]{0.00f, 0.00f, 0.00f})));
        ModelLocators.register("hollow_spawn", Map.ofEntries(Map.entry("feet", new float[]{0.00f, 0.00f, 0.00f}), Map.entry("head", new float[]{0.00f, 28.00f, -3.00f})));
        ModelLocators.register("hollow_bolt", Map.ofEntries(Map.entry("trail", new float[]{0.00f, 2.00f, 3.50f})));
    }
}
