package net.teamaof.skylorebosses.bosses.amanita;

/** GENERATED by bosses/amanita/tools/export_to_mod.py: Amanita sound ids (registered as skylore_bosses:amanita.<id>). */
public final class AmanitaSoundIds {
    public static final String[] ALL = {
            "absorb",
            "bared",
            "bloom.open",
            "bloom.windup",
            "bolt.cast",
            "bolt.impact",
            "bolt.windup",
            "brazier.light",
            "call.root",
            "dash.go",
            "dash.smother",
            "dash.windup",
            "death",
            "deep.bloom",
            "deep.windup",
            "eater.burrow",
            "eater.chew",
            "eater.death",
            "eater.emerge",
            "eater.gulp",
            "full.windup",
            "howl",
            "howl.inhale",
            "hurt",
            "idle.breathe",
            "knocker",
            "lash.swing",
            "lash.windup",
            "lockdown",
            "recoil",
            "rise",
            "sink",
            "slam.wave",
            "slam.windup",
            "snuff.full",
            "snuff.gather",
            "snuff.hiss",
            "snuff.pulse",
            "snuff.windup",
            "spawn.dissolve",
            "spawn.emerge",
            "spawn.swing",
            "veil.bloom",
            "veil.windup",
            "victory"
    };

    private AmanitaSoundIds() {}
}
