package net.teamaof.skylorebosses.bosses.nullrouter;

import java.util.Map;
import net.teamaof.skylorebosses.core.fx.ModelLocators;

/** GENERATED by bosses/null_router/tools/export_to_mod.py from the Blockbench specs. Rest-pose locators in model pixels. */
public final class RouterLocators {
    private RouterLocators() {}

    public static void register() {
        ModelLocators.register("null_router", Map.ofEntries(Map.entry("lens", new float[]{0.00f, 28.50f, -9.00f}), Map.entry("port_l", new float[]{-12.50f, 26.00f, -5.80f}), Map.entry("port_r", new float[]{12.50f, 26.00f, -5.80f}), Map.entry("crown", new float[]{0.00f, 44.00f, -4.50f}), Map.entry("antenna", new float[]{-5.50f, 52.80f, 3.50f}), Map.entry("port_b", new float[]{0.00f, 7.00f, 0.00f}), Map.entry("core", new float[]{0.00f, 24.00f, 0.00f}), Map.entry("base", new float[]{0.00f, 0.00f, 0.00f})));
        ModelLocators.register("retry_packet", Map.ofEntries(Map.entry("core", new float[]{0.00f, 6.50f, 0.00f})));
    }
}
