"""Copy the Static Deacon Blockbench exports into the mod and generate the derived assets: geo/animations/textures,
DeaconLocators.java, DeaconSoundIds.java, particle descriptions, block/item textures (from the Codex-painted sources in
textures/src/, see codex_textures.py), synthesized sounds and this boss's sounds.json entries.
    python export_to_mod.py            # everything
    python export_to_mod.py --no-sounds"""
import json, os, shutil, sys
import numpy as np
from PIL import Image
import boss_env
import models, sounds
from sounds import bell, crystal, crackle, chant, hum, hiss, whip, boom, swell, clicks, choir

ROOT = boss_env.BOSS_DIR
REPO = boss_env.REPO
MOD = os.path.join(REPO, "src", "main")
NS = "skylore_bosses"
BOSS = "static_deacon"
ASSETS = os.path.join(MOD, "resources", "assets", NS)
JAVA = os.path.join(MOD, "java", "net", "teamaof", "skylorebosses", "bosses", "staticdeacon")
SRC = boss_env.TEXTURE_SRC
SOUND_IDS = os.path.join(ROOT, "tools", "sound_ids.txt")

ENTITY_MODELS = ["static_deacon", "static_bolt", "homing_shard"]
FACTORIES = {f.__name__: f for f in models.ALL}

# sounds fired from Java rather than animation keyframes
EXTRA_SOUNDS = ["lockdown", "bell", "flagstone.live", "flagstone.reseed", "flagstone.desecrate", "vigil.begin", "vigil.break",
                "reseed.toll", "reseed.chant", "chime", "pulse.release", "lash.swing", "bolt.cast", "bolt.impact", "shatter.crack",
                "shard.cast", "shard.break", "pull.snap", "pull.yank", "beam.loop", "absorb", "step", "death", "victory"]

# first matching key wins, so specific ids come before the words they contain
sounds.EXTRA_RULES = [
    ("idle.hum", chant, {"d": 3.0, "f": 73}, 1.0), ("vesting.rise", choir, {"d": 5.0}),
    ("chime.windup", swell, {"d": 1.8}), ("reseed.toll", bell, {"d": 4.0, "f": 110}), ("lockdown", bell, {"d": 3.5, "f": 147}),
    ("bell", bell, {"d": 2.5, "f": 523}), ("chime", bell, {"d": 3.0, "f": 330}),
    ("pulse.charge", swell, {"d": 2.0}), ("pulse.release", bell, {"d": 1.6, "f": 196}),
    ("lash.windup", crystal, {"d": 0.6, "f": 1400}), ("lash.swing", whip, {"d": 0.35}),
    ("bolt.windup", crackle, {"d": 1.0, "density": 30}), ("bolt.cast", crystal, {"d": 0.4, "f": 2200}),
    ("bolt.impact", crackle, {"d": 0.4, "density": 120}),
    ("shatter.windup", crackle, {"d": 1.5, "density": 40}), ("shatter.crack", crystal, {"d": 0.5, "f": 900}),
    ("shard.windup", crystal, {"d": 1.4, "f": 1600}), ("shard.cast", crystal, {"d": 0.5, "f": 2600}),
    ("shard.break", crystal, {"d": 0.5, "f": 3000}),
    ("pull.windup", whip, {"d": 1.0}), ("pull.yank", whip, {"d": 0.4}, 0.8), ("pull.snap", clicks, {"d": 0.3, "count": 4, "lo": 600, "hi": 5000}),
    ("beam.windup", chant, {"d": 2.0, "f": 147}), ("beam.loop", chant, {"d": 1.0, "f": 196}),
    ("reseed.begin", chant, {"d": 2.0, "f": 110}), ("reseed.chant", chant, {"d": 1.0, "f": 123}),
    ("flagstone.live", crystal, {"d": 1.0, "f": 1200}), ("flagstone.reseed", swell, {"d": 1.0}),
    ("flagstone.desecrate", boom, {"d": 0.9, "f0": 150, "f1": 60, "crack": 1.0}),
    ("vigil.begin", bell, {"d": 3.0, "f": 98}), ("vigil.break", crystal, {"d": 1.2, "f": 700}),
    ("absorb", crystal, {"d": 0.3, "f": 2400}), ("step", crackle, {"d": 0.8, "density": 80}),
    ("hurt", crystal, {"d": 0.4, "f": 1000}), ("death", bell, {"d": 6.0, "f": 65}), ("victory", choir, {"d": 5.0}),
]


def mk(*p):
    d = os.path.join(*p)
    os.makedirs(d, exist_ok=True)
    return d


def copy_models():
    for n in ENTITY_MODELS:
        src = os.path.join(boss_env.MODELS, n)
        shutil.copy(os.path.join(src, f"{n}.geo.json"), os.path.join(mk(ASSETS, "geo", "entity", BOSS), f"{n}.geo.json"))
        shutil.copy(os.path.join(src, f"{n}.animation.json"), os.path.join(mk(ASSETS, "animations", "entity", BOSS), f"{n}.animation.json"))
        shutil.copy(os.path.join(src, f"{n}.png"), os.path.join(mk(ASSETS, "textures", "entity", BOSS), f"{n}.png"))
        shutil.copy(os.path.join(src, f"{n}_glowmask.png"), os.path.join(mk(ASSETS, "textures", "entity", BOSS), f"{n}_glowmask.png"))


def _pairs(locs):
    return [f'"{l["name"]}", new float[]{{{l["pos"][0]:.2f}f, {l["pos"][1]:.2f}f, {l["pos"][2]:.2f}f}}' for l in locs]


def locators_java():
    lines, sound_ids = [], set()
    for n in ENTITY_MODELS:
        m = FACTORIES[n]()
        for a in m.anims:
            for s in a["sounds"]:
                sound_ids.add(s["effect"].split(":", 1)[1])
        lines.append(f'        ModelLocators.register("{n}", Map.ofEntries({", ".join("Map.entry(" + e + ")" for e in _pairs(m.locators))}));')
    src = f"""package net.teamaof.skylorebosses.bosses.staticdeacon;

import java.util.Map;
import net.teamaof.skylorebosses.core.fx.ModelLocators;

/** GENERATED by bosses/static_deacon/tools/export_to_mod.py from the Blockbench specs. Rest-pose locators in model pixels. */
public final class DeaconLocators {{
    private DeaconLocators() {{}}

    public static void register() {{
{chr(10).join(lines)}
    }}
}}
"""
    with open(os.path.join(mk(JAVA), "DeaconLocators.java"), "w") as f:
        f.write(src)
    return sorted(sound_ids | set(EXTRA_SOUNDS))


# ---------------- particle descriptions (sprites are the shared glow/spark/puff sets) ----------------
PARTICLES = {"static_dust": ("spark", 3), "communion_mote": ("glow", 3), "beryl_glint": ("spark", 3), "litany_light": ("glow", 3)}


def particles():
    pdir = mk(ASSETS, "particles")
    for name, (fam, n) in PARTICLES.items():
        with open(os.path.join(pdir, f"{name}.json"), "w") as f:
            json.dump({"textures": [f"{NS}:{fam}_{i}" for i in range(n)]}, f, indent=2)


# ---------------- block & item textures (Codex sources) ----------------
BLOCK_TEXTURES = ["consecrated_endstone", "desecrated_endstone", "altar_plinth_top", "altar_plinth_side", "crypt_tile", "crypt_subfloor",
                  "crypt_wall", "crypt_pillar_side", "crypt_pillar_top", "beryl_lamp", "crypt_pew", "sacristy_bell", "crypt_grate"]


def dim_glyphs(a):
    """Unlit consecrated endstone (a reseeding flagstone): the violet glyph pixels fade toward the stone."""
    rgb = a[..., :3].astype(float)
    violet = (rgb[..., 2] > rgb[..., 1] + 25) & (rgb[..., 0] > rgb[..., 1] - 10)
    stone = np.array([200, 196, 150], float)
    rgb[violet] = rgb[violet] * 0.35 + stone * 0.65
    out = a.copy()
    out[..., :3] = rgb.clip(0, 255).astype(np.uint8)
    return out


def blocks_and_items():
    bt = mk(ASSETS, "textures", "block", BOSS)
    it = mk(ASSETS, "textures", "item", BOSS)
    for n in BLOCK_TEXTURES:
        shutil.copy(os.path.join(SRC, f"{n}.png"), os.path.join(bt, f"{n}.png"))
    a = np.array(Image.open(os.path.join(SRC, "consecrated_endstone.png")).convert("RGBA"))
    Image.fromarray(dim_glyphs(a)).save(os.path.join(bt, "consecrated_endstone_unlit.png"))
    shutil.copy(os.path.join(SRC, "static_thurible.png"), os.path.join(it, "static_thurible.png"))


# ---------------- sounds ----------------
def sound_files(ids, synth=True):
    sdir = mk(ASSETS, "sounds", BOSS)
    path = os.path.join(ASSETS, "sounds.json")
    j = json.load(open(path)) if os.path.exists(path) else {}
    j = {k: v for k, v in j.items() if not k.startswith(BOSS + ".")}
    for sid in ids:
        fname = sid.replace(".", "_")
        if synth:
            sounds.write(sid, os.path.join(sdir, f"{fname}.ogg"))
        entry = {"subtitle": f"subtitles.{NS}.{BOSS}.{sid}", "sounds": [{"name": f"{NS}:{BOSS}/{fname}"}]}
        if sid.split(".")[0] in ("lockdown", "reseed", "vigil", "chime", "death", "victory", "vesting"):
            entry["sounds"][0]["attenuation_distance"] = 64
        j[f"{BOSS}.{sid}"] = entry
    with open(path, "w") as f:
        json.dump(dict(sorted(j.items())), f, indent=2)
    with open(SOUND_IDS, "w") as f:
        f.write("\n".join(ids))


def sound_ids_java(ids):
    body = ",\n            ".join(f'"{s}"' for s in ids)
    src = f"""package net.teamaof.skylorebosses.bosses.staticdeacon;

/** GENERATED by bosses/static_deacon/tools/export_to_mod.py: Static Deacon sound ids (registered as skylore_bosses:static_deacon.<id>). */
public final class DeaconSoundIds {{
    public static final String[] ALL = {{
            {body}
    }};

    private DeaconSoundIds() {{}}
}}
"""
    with open(os.path.join(mk(JAVA), "DeaconSoundIds.java"), "w") as f:
        f.write(src)


if __name__ == "__main__":
    copy_models()
    ids = locators_java()
    particles()
    blocks_and_items()
    sound_files(ids, synth="--no-sounds" not in sys.argv)
    sound_ids_java(ids)
    print(len(ids), "sounds;", len(ENTITY_MODELS), "models exported")
