package net.teamaof.skylorebosses.bosses.matriscalyx;

import java.util.Map;
import net.teamaof.skylorebosses.core.fx.ModelLocators;

/** GENERATED by bosses/matris_calyx/tools/export_to_mod.py from the Blockbench specs. Rest-pose locators in model pixels. */
public final class MatrisLocators {
    private MatrisLocators() {}

    public static void register() {
        ModelLocators.register("grasping_arm", Map.ofEntries(Map.entry("core", new float[]{0.00f, 18.00f, -12.00f}), Map.entry("base", new float[]{0.00f, 2.00f, -16.00f}), Map.entry("grip", new float[]{0.00f, 156.00f, 0.00f})));
        ModelLocators.register("slam_arm", Map.ofEntries(Map.entry("core", new float[]{0.00f, 18.00f, -15.00f}), Map.entry("base", new float[]{0.00f, 2.00f, -16.00f}), Map.entry("impact", new float[]{0.00f, 89.00f, -8.00f})));
        ModelLocators.register("charging_arm", Map.ofEntries(Map.entry("core", new float[]{0.00f, 36.00f, 10.00f}), Map.entry("ram", new float[]{0.00f, 22.00f, -36.00f}), Map.entry("base", new float[]{0.00f, 1.00f, 0.00f}), Map.entry("back", new float[]{0.00f, 20.00f, 22.00f})));
        ModelLocators.register("mouth_arm", Map.ofEntries(Map.entry("core", new float[]{0.00f, 18.00f, -13.00f}), Map.entry("base", new float[]{0.00f, 2.00f, -16.00f}), Map.entry("maw", new float[]{0.00f, 108.00f, -14.00f})));
        ModelLocators.register("spitting_arm", Map.ofEntries(Map.entry("core", new float[]{0.00f, 18.00f, -13.00f}), Map.entry("base", new float[]{0.00f, 2.00f, -16.00f}), Map.entry("muzzle", new float[]{0.00f, 91.00f, -30.00f})));
        ModelLocators.register("nerve_arm", Map.ofEntries(Map.entry("core", new float[]{0.00f, 18.00f, -12.00f}), Map.entry("base", new float[]{0.00f, 2.00f, -16.00f}), Map.entry("ganglion", new float[]{0.00f, 121.00f, 0.00f}), Map.entry("tip_0", new float[]{25.00f, 130.00f, 0.00f}), Map.entry("tip_1", new float[]{12.50f, 132.00f, 21.65f}), Map.entry("tip_2", new float[]{-12.50f, 130.00f, 21.65f}), Map.entry("tip_3", new float[]{-25.00f, 132.00f, 0.00f}), Map.entry("tip_4", new float[]{-12.50f, 130.00f, -21.65f}), Map.entry("tip_5", new float[]{12.50f, 132.00f, -21.65f})));
        ModelLocators.register("calyx_bloom", Map.ofEntries(Map.entry("vent_0", new float[]{29.44f, 18.00f, 17.00f}), Map.entry("vent_1", new float[]{0.00f, 18.00f, 34.00f}), Map.entry("vent_2", new float[]{-29.44f, 18.00f, 17.00f}), Map.entry("vent_3", new float[]{-29.44f, 18.00f, -17.00f}), Map.entry("vent_4", new float[]{-0.00f, 18.00f, -34.00f}), Map.entry("vent_5", new float[]{29.44f, 18.00f, -17.00f}), Map.entry("lobe_tip_0", new float[]{8.00f, 80.00f, 0.00f}), Map.entry("lobe_tip_1", new float[]{8.00f, 80.00f, 0.00f}), Map.entry("lobe_tip_2", new float[]{8.00f, 80.00f, 0.00f}), Map.entry("lobe_tip_3", new float[]{8.00f, 80.00f, 0.00f}), Map.entry("lobe_tip_4", new float[]{8.00f, 80.00f, 0.00f}), Map.entry("lobe_tip_5", new float[]{8.00f, 80.00f, 0.00f}), Map.entry("laser", new float[]{0.00f, 116.00f, -26.00f}), Map.entry("glint", new float[]{5.00f, 121.00f, -24.00f}), Map.entry("drip_0", new float[]{19.11f, 41.00f, 12.36f}), Map.entry("drip_1", new float[]{4.43f, 41.00f, 17.80f}), Map.entry("drip_2", new float[]{-14.67f, 41.00f, 15.44f}), Map.entry("drip_3", new float[]{-19.11f, 41.00f, 7.64f}), Map.entry("drip_4", new float[]{-4.43f, 41.00f, 2.20f}), Map.entry("drip_5", new float[]{14.67f, 41.00f, 4.56f})));
        ModelLocators.register("bile_glob", Map.ofEntries(Map.entry("trail", new float[]{0.00f, 4.00f, 5.00f})));
        ModelLocators.register("spore_thrall", Map.ofEntries(Map.entry("back", new float[]{0.00f, 27.00f, 6.00f}), Map.entry("mouth", new float[]{0.00f, 25.00f, -6.00f}), Map.entry("feet", new float[]{0.00f, 0.50f, 0.00f})));
        ModelLocators.register("spore_mite", Map.ofEntries(Map.entry("sac", new float[]{0.00f, 6.00f, 3.00f})));
        ModelLocators.register("infected_drifter", Map.ofEntries(Map.entry("top", new float[]{0.00f, 31.00f, 0.00f}), Map.entry("maw", new float[]{0.00f, 12.00f, 0.00f}), Map.entry("hook", new float[]{4.14f, -10.00f, 1.75f})));
        ModelLocators.register("spore_vent", Map.ofEntries(Map.entry("spout", new float[]{0.00f, 41.00f, 0.00f}), Map.entry("base", new float[]{0.00f, 2.00f, 0.00f})));
    }
}
