package net.teamaof.skylorebosses.bosses.staticdeacon;

import java.util.Map;
import net.teamaof.skylorebosses.core.fx.ModelLocators;

/** GENERATED by bosses/static_deacon/tools/export_to_mod.py from the Blockbench specs. Rest-pose locators in model pixels. */
public final class DeaconLocators {
    private DeaconLocators() {}

    public static void register() {
        ModelLocators.register("static_deacon", Map.ofEntries(Map.entry("core", new float[]{0.00f, 36.20f, -5.50f}), Map.entry("head", new float[]{0.00f, 46.50f, -3.00f}), Map.entry("halo", new float[]{0.00f, 50.00f, 6.80f}), Map.entry("hand_l", new float[]{-9.20f, 14.00f, -1.00f}), Map.entry("hand_r", new float[]{9.20f, 19.00f, -0.50f}), Map.entry("censer", new float[]{9.20f, 4.00f, -0.50f}), Map.entry("feet", new float[]{0.00f, 0.00f, 0.00f})));
        ModelLocators.register("static_bolt", Map.ofEntries(Map.entry("trail", new float[]{0.00f, 2.00f, 3.50f})));
        ModelLocators.register("homing_shard", Map.ofEntries(Map.entry("trail", new float[]{0.00f, 2.50f, 3.00f})));
    }
}
