package net.teamaof.skylorebosses.bosses.staticdeacon;

/** GENERATED by bosses/static_deacon/tools/export_to_mod.py: Static Deacon sound ids (registered as skylore_bosses:static_deacon.<id>). */
public final class DeaconSoundIds {
    public static final String[] ALL = {
            "absorb",
            "beam.loop",
            "beam.windup",
            "bell",
            "bolt.cast",
            "bolt.impact",
            "bolt.windup",
            "chime",
            "chime.windup",
            "death",
            "flagstone.desecrate",
            "flagstone.live",
            "flagstone.reseed",
            "hurt",
            "idle.hum",
            "lash.swing",
            "lash.windup",
            "lockdown",
            "pull.snap",
            "pull.windup",
            "pull.yank",
            "pulse.charge",
            "pulse.release",
            "reseed.begin",
            "reseed.chant",
            "reseed.toll",
            "shard.break",
            "shard.cast",
            "shard.windup",
            "shatter.crack",
            "shatter.windup",
            "step",
            "vesting.rise",
            "victory",
            "vigil.begin",
            "vigil.break"
    };

    private DeaconSoundIds() {}
}
