"""Copy the Overhead Blockbench exports into the mod and generate the derived assets: geo/animations/textures,
OverheadLocators.java, OverheadSoundIds.java, particle descriptions, block/item textures, synthesized sounds and
this boss's sounds.json entries.
    python export_to_mod.py            # everything
    python export_to_mod.py --no-sounds"""
import json, os, shutil, sys
import numpy as np
from PIL import Image
import boss_env
import texture, models, sounds
from sounds import (boom, clank, servo, hum, klaxon, siren, autocannon, beep, electric, zap, hiss, whip, ping,
                    laser_charge, laser_loop, choir)

ROOT = boss_env.BOSS_DIR
REPO = boss_env.REPO
MOD = os.path.join(REPO, "src", "main")
NS = "skylore_bosses"
BOSS = "overhead"
ASSETS = os.path.join(MOD, "resources", "assets", NS)
JAVA = os.path.join(MOD, "java", "net", "teamaof", "skylorebosses", "bosses", "overhead")
SOUND_IDS = os.path.join(ROOT, "tools", "sound_ids.txt")

ENTITY_MODELS = ["overhead", "howitzer_shell", "seeker_missile"]
BLOCK_MODELS = ["generator_pylon"]
FACTORIES = {f.__name__: f for f in models.ALL}

# sounds fired from Java rather than animation keyframes
EXTRA_SOUNDS = ["shell.impact", "missile.impact", "missile.lock", "missile.launch", "laser.loop", "strafe.fire", "flare.burst",
                "overcharge.discharge", "carpet.impact", "rearm.siren", "flak.fire", "flak.burst", "shield.deflect",
                "pylon.online", "lockdown.gate", "victory"]

sounds.EXTRA_RULES = [
    ("rotor.loop", hum, {"d": 2.0, "f": 45}), ("brownout", electric, {"d": 1.2}, 0.8),
    ("power.charge", servo, {"d": 3.0, "f0": 80, "f1": 600}), ("power.pulse", boom, {"d": 1.2, "f0": 120, "f1": 40}),
    ("howitzer.load", clank, {"d": 0.8}), ("howitzer.fire", boom, {"d": 1.6, "f0": 90, "f1": 30}),
    ("shell.impact", boom, {"d": 1.8}), ("missile.open", servo, {"d": 0.8, "f0": 300, "f1": 500}),
    ("missile.lock", beep, {"d": 0.6}), ("missile.launch", hiss, {"d": 0.6, "lo": 800, "hi": 8000, "a": 0.01}),
    ("missile.impact", boom, {"d": 1.0, "f0": 140, "f1": 50}), ("laser.charge", laser_charge, {}),
    ("laser.loop", laser_loop, {}), ("laser.vent", hiss, {"d": 1.4, "lo": 400, "hi": 6000, "a": 0.02}),
    ("strafe.spinup", servo, {"d": 1.5, "f0": 100, "f1": 1200}), ("strafe.fire", autocannon, {}),
    ("flare.launch", whip, {"d": 0.5}), ("flare.burst", ping, {"d": 1.0}),
    ("overcharge.charge", electric, {"d": 2.0}), ("overcharge.discharge", zap, {"d": 1.0}),
    ("carpet.klaxon", klaxon, {"d": 3.0}), ("carpet.impact", boom, {"d": 1.0, "f0": 110, "f1": 40}),
    ("shield.pulse", boom, {"d": 1.2, "f0": 200, "f1": 60}), ("shield.deflect", clank, {"d": 0.3}, 1.6),
    ("rearm.siren", siren, {"d": 3.0}), ("flak.fire", autocannon, {"d": 0.3}, 0.8),
    ("flak.burst", boom, {"d": 0.8, "f0": 180, "f1": 70}), ("pylon.hum", hum, {"d": 2.0, "f": 120}),
    ("pylon.hit", clank, {"d": 0.5}), ("pylon.break", boom, {"d": 2.2, "f0": 70, "f1": 25}),
    ("pylon.rebuild", servo, {"d": 1.0, "f0": 200, "f1": 260}), ("pylon.online", servo, {"d": 1.2, "f0": 150, "f1": 900}),
    ("lockdown.gate", clank, {"d": 1.5}, 0.6), ("victory", choir, {"d": 4.0}),
    ("death", boom, {"d": 3.0, "f0": 60, "f1": 20}), ("hurt", clank, {"d": 0.35}, 1.2),
]


def mk(*p):
    d = os.path.join(*p)
    os.makedirs(d, exist_ok=True)
    return d


def copy_models():
    for kind, names in (("entity", ENTITY_MODELS), ("block", BLOCK_MODELS)):
        for n in names:
            src = os.path.join(boss_env.MODELS, n)
            shutil.copy(os.path.join(src, f"{n}.geo.json"), os.path.join(mk(ASSETS, "geo", kind, BOSS), f"{n}.geo.json"))
            shutil.copy(os.path.join(src, f"{n}.animation.json"), os.path.join(mk(ASSETS, "animations", kind, BOSS), f"{n}.animation.json"))
            shutil.copy(os.path.join(src, f"{n}.png"), os.path.join(mk(ASSETS, "textures", kind, BOSS), f"{n}.png"))
            shutil.copy(os.path.join(src, f"{n}_glowmask.png"), os.path.join(mk(ASSETS, "textures", kind, BOSS), f"{n}_glowmask.png"))


def _pairs(locs):
    return [f'"{l["name"]}", new float[]{{{l["pos"][0]:.2f}f, {l["pos"][1]:.2f}f, {l["pos"][2]:.2f}f}}' for l in locs]


def locators_java():
    lines, sound_ids = [], set()
    for n in ENTITY_MODELS + BLOCK_MODELS:
        m = FACTORIES[n]()
        for a in m.anims:
            for s in a["sounds"]:
                sound_ids.add(s["effect"].split(":", 1)[1])
        lines.append(f'        ModelLocators.register("{n}", Map.ofEntries({", ".join("Map.entry(" + e + ")" for e in _pairs(m.locators))}));')
    src = f"""package net.teamaof.skylorebosses.bosses.overhead;

import java.util.Map;
import net.teamaof.skylorebosses.core.fx.ModelLocators;

/** GENERATED by bosses/overhead/tools/export_to_mod.py from the Blockbench specs. Rest-pose locators in model pixels. */
public final class OverheadLocators {{
    private OverheadLocators() {{}}

    public static void register() {{
{chr(10).join(lines)}
    }}
}}
"""
    with open(os.path.join(mk(JAVA), "OverheadLocators.java"), "w") as f:
        f.write(src)
    return sorted(sound_ids | set(EXTRA_SOUNDS))


# ---------------- particle descriptions (sprites are the shared puff/spark/glow sets) ----------------
PARTICLES = {"smoke": ("puff", 4), "spark": ("spark", 3), "muzzle_flash": ("glow", 3), "grid_arc": ("spark", 3),
             "ember": ("glow", 3), "shield": ("glow", 3), "target_mark": ("glow", 3), "rail_mark": ("glow", 3),
             "red_beam": ("glow", 3)}


def particles():
    pdir = mk(ASSETS, "particles")
    for name, (fam, n) in PARTICLES.items():
        with open(os.path.join(pdir, f"{name}.json"), "w") as f:
            json.dump({"textures": [f"{NS}:{fam}_{i}" for i in range(n)]}, f, indent=2)


# ---------------- block & item textures ----------------
def tile16(mat, seed=0):
    atlas, _ = texture.build(seed=11)
    ox, oy = texture.tile_origin(mat)
    rng = np.random.default_rng(seed)
    dx, dy = rng.integers(0, 48, 2)
    return atlas.crop((ox + dx, oy + dy, ox + dx + 16, oy + dy + 16))


def frame(a, color, w=1):
    a[:w, :, :3] = color
    a[-w:, :, :3] = color
    a[:, :w, :3] = color
    a[:, -w:, :3] = color
    return a


def blocks_and_items():
    bt = mk(ASSETS, "textures", "block", BOSS)
    it = mk(ASSETS, "textures", "item", BOSS)
    # floor plating: riveted steel panel
    a = np.array(tile16("steel", 1))
    a = frame(a, (70, 74, 80))
    for x, y in ((2, 2), (13, 2), (2, 13), (13, 13)):
        a[y, x, :3] = (200, 204, 210)
    Image.fromarray(a).save(os.path.join(bt, "yard_plating.png"))
    # hazard plating: diagonal yellow/black
    a = np.zeros((16, 16, 4), np.uint8)
    yy, xx = np.mgrid[0:16, 0:16]
    stripe = ((xx + yy) // 4) % 2 == 0
    a[..., :3] = np.where(stripe[..., None], np.array((226, 180, 30)), np.array((34, 30, 26)))
    a[..., 3] = 255
    noise = np.random.default_rng(3).integers(-12, 12, (16, 16, 1))
    a[..., :3] = np.clip(a[..., :3].astype(int) + noise, 0, 255)
    Image.fromarray(a).save(os.path.join(bt, "hazard_plating.png"))
    # wall: Noven teal panel with a pale stencil band
    a = np.array(tile16("noven", 2))
    a = frame(a, (20, 60, 64))
    a[6:9, 1:15, :3] = (190, 200, 190)
    a[7, 3:13:2, :3] = (40, 60, 60)
    Image.fromarray(a).save(os.path.join(bt, "yard_wall.png"))
    # shutter: warning red slats
    a = np.array(tile16("warning", 3))
    for y in range(0, 16, 4):
        a[y, :, :3] = (60, 14, 12)
    a[:, 7:9, :3] = (226, 180, 30)
    Image.fromarray(a).save(os.path.join(bt, "yard_shutter.png"))
    # crate: plank faces with a Noven stripe and a dark frame
    rng = np.random.default_rng(4)
    a = np.zeros((16, 16, 4), np.uint8)
    base = np.array((132, 96, 60))
    for y in range(16):
        a[y, :, :3] = np.clip(base + rng.integers(-10, 10) + (-24 if y % 5 == 0 else 0), 0, 255)
    a[..., 3] = 255
    a = frame(a, (70, 48, 30), 2)
    for k in range(16):
        a[k, k, :3] = (70, 48, 30)
    a[7:9, :, :3] = (46, 110, 112)
    Image.fromarray(a).save(os.path.join(bt, "yard_crate.png"))
    # console: dark steel with an amber screen (front) and plain sides
    side = np.array(tile16("steel_dark", 5))
    Image.fromarray(side).save(os.path.join(bt, "yard_console_side.png"))
    a = side.copy()
    a[3:10, 3:13, :3] = (20, 24, 28)
    a[4:9, 4:12, :3] = (255, 170, 40)
    for y in (5, 7):
        a[y, 5:11, :3] = (150, 80, 10)
    a[11:13, 4:7, :3] = (176, 40, 34)
    a[11:13, 9:12, :3] = (90, 220, 255)
    Image.fromarray(a).save(os.path.join(bt, "yard_console_front.png"))
    Image.fromarray(np.array(tile16("steel", 6))).save(os.path.join(bt, "pylon_casing.png"))
    # items: targeting core (red lens in a steel ring), pylon icon
    a = np.zeros((16, 16, 4), np.uint8)
    r = np.hypot(xx - 7.5, yy - 7.5)
    a[r < 7.2] = (62, 66, 74, 255)
    a[r < 5.5] = (128, 134, 140, 255)
    a[r < 4.2] = (150, 10, 10, 255)
    a[r < 3.0] = (255, 60, 40, 255)
    a[r < 1.2] = (255, 210, 170, 255)
    Image.fromarray(a).save(os.path.join(it, "targeting_core.png"))
    a = np.zeros((16, 16, 4), np.uint8)
    a[12:16, 1:15] = (62, 66, 74, 255)
    a[12, 1:15] = (226, 180, 30, 255)
    a[3:12, 6:10] = (128, 134, 140, 255)
    for y in (4, 6, 8, 10):
        a[y, 4:12] = (190, 110, 60, 255)
    a[0:3, 5:11] = (90, 220, 255, 255)
    Image.fromarray(a).save(os.path.join(it, "generator_pylon.png"))


# ---------------- sounds ----------------
def sound_files(ids, synth=True):
    sdir = mk(ASSETS, "sounds", BOSS)
    path = os.path.join(ASSETS, "sounds.json")
    j = json.load(open(path)) if os.path.exists(path) else {}
    j = {k: v for k, v in j.items() if not k.startswith(BOSS + ".")}
    for sid in ids:
        fname = sid.replace(".", "_")
        if synth:
            sounds.write(sid, os.path.join(sdir, f"{fname}.ogg"))
        entry = {"subtitle": f"subtitles.{NS}.{BOSS}.{sid}", "sounds": [{"name": f"{NS}:{BOSS}/{fname}"}]}
        if sid.split(".")[0] in ("carpet", "rearm", "lockdown", "victory", "howitzer", "shell", "pylon", "power", "death"):
            entry["sounds"][0]["attenuation_distance"] = 96
        j[f"{BOSS}.{sid}"] = entry
    with open(path, "w") as f:
        json.dump(dict(sorted(j.items())), f, indent=2)
    with open(SOUND_IDS, "w") as f:
        f.write("\n".join(ids))


def sound_ids_java(ids):
    body = ",\n            ".join(f'"{s}"' for s in ids)
    src = f"""package net.teamaof.skylorebosses.bosses.overhead;

/** GENERATED by bosses/overhead/tools/export_to_mod.py: Overhead sound ids (registered as skylore_bosses:overhead.<id>). */
public final class OverheadSoundIds {{
    public static final String[] ALL = {{
            {body}
    }};

    private OverheadSoundIds() {{}}
}}
"""
    with open(os.path.join(mk(JAVA), "OverheadSoundIds.java"), "w") as f:
        f.write(src)


if __name__ == "__main__":
    copy_models()
    ids = locators_java()
    particles()
    blocks_and_items()
    sound_files(ids, synth="--no-sounds" not in sys.argv)
    sound_ids_java(ids)
    print(len(ids), "sounds;", len(ENTITY_MODELS) + len(BLOCK_MODELS), "models exported")
