"""Copy the Blockbench exports into the NeoForge mod and generate the derived assets:
models/animations/textures, the Java locator table, particle sprites + descriptions,
block/item textures, sounds (synthesised OGG) and sounds.json.
    python export_to_mod.py            # everything
    python export_to_mod.py --no-sounds"""
import json, os, shutil, sys
import numpy as np
from PIL import Image
import boss_env
import texture, arms, bloom, props, adds, lib, sounds

ROOT = boss_env.BOSS_DIR          # bosses/matris_calyx
REPO = boss_env.REPO
MOD = os.path.join(REPO, "src", "main")
NS = "skylore_bosses"
BOSS = "matris_calyx"
ASSETS = os.path.join(MOD, "resources", "assets", NS)
JAVA = os.path.join(MOD, "java", "net", "teamaof", "skylorebosses", "bosses", "matriscalyx")
SOUND_IDS = os.path.join(ROOT, "tools", "sound_ids.txt")

ENTITY_MODELS = ["grasping_arm", "slam_arm", "charging_arm", "mouth_arm", "spitting_arm", "nerve_arm",
                 "calyx_bloom", "bile_glob", "spore_thrall", "spore_mite", "infected_drifter"]
BLOCK_MODELS = ["spore_vent"]
FACTORIES = {f.__name__: f for f in arms.ALL + bloom.ALL + props.ALL + adds.ALL}
NAME_TO_FACTORY = {"grasping_arm": "grasping", "slam_arm": "slam", "charging_arm": "charging", "mouth_arm": "mouth",
                   "spitting_arm": "spitting", "nerve_arm": "nerve", "calyx_bloom": "bloom", "bile_glob": "bile_glob",
                   "spore_vent": "spore_vent", "spore_thrall": "spore_thrall", "spore_mite": "spore_mite",
                   "infected_drifter": "infected_drifter"}

EXTRA_SOUNDS = ["attack.peristalsis.warn", "attack.bile_rain.warn", "attack.retina_flash.warn", "attack.root_grip.warn",
                "attack.swallow.warn", "attack.spore_exhale.warn", "ambient.stomach", "arm.thunk", "infection.rise",
                "infection.taken", "syringe.inject", "encounter.awaken", "encounter.victory"]


def mk(*p):
    d = os.path.join(*p)
    os.makedirs(d, exist_ok=True)
    return d


def copy_models():
    for kind, names in (("entity", ENTITY_MODELS), ("block", BLOCK_MODELS)):
        for n in names:
            src = os.path.join(boss_env.MODELS, n)
            shutil.copy(os.path.join(src, f"{n}.geo.json"), os.path.join(mk(ASSETS, "geo", kind, BOSS), f"{n}.geo.json"))
            shutil.copy(os.path.join(src, f"{n}.animation.json"), os.path.join(mk(ASSETS, "animations", kind, BOSS), f"{n}.animation.json"))
            shutil.copy(os.path.join(src, f"{n}.png"), os.path.join(mk(ASSETS, "textures", kind, BOSS), f"{n}.png"))
            shutil.copy(os.path.join(src, f"{n}_glowmask.png"), os.path.join(mk(ASSETS, "textures", kind, BOSS), f"{n}_glowmask.png"))


def locators_java():
    lines = []
    sound_ids = set()
    for n in ENTITY_MODELS + BLOCK_MODELS:
        m = FACTORIES[NAME_TO_FACTORY[n]]()
        for a in m.anims:
            for s in a["sounds"]:
                sound_ids.add(s["effect"].split(":", 1)[1])
        lines.append(f'        ModelLocators.register("{n}", Map.ofEntries({", ".join("Map.entry(" + e + ")" for e in _pairs(m.locators))}));')
    src = f"""package net.teamaof.skylorebosses.bosses.matriscalyx;

import java.util.Map;
import net.teamaof.skylorebosses.core.fx.ModelLocators;

/** GENERATED by bosses/matris_calyx/tools/export_to_mod.py from the Blockbench specs. Rest-pose locators in model pixels. */
public final class MatrisLocators {{
    private MatrisLocators() {{}}

    public static void register() {{
{chr(10).join(lines)}
    }}
}}
"""
    with open(os.path.join(mk(JAVA), "MatrisLocators.java"), "w") as f:
        f.write(src)
    return sorted(sound_ids | set(EXTRA_SOUNDS))


def _pairs(locs):
    return [f'"{l["name"]}", new float[]{{{l["pos"][0]:.2f}f, {l["pos"][1]:.2f}f, {l["pos"][2]:.2f}f}}' for l in locs]


# ---------------- particle sprites ----------------
PARTICLES = {  # name -> sprite family
    "bile_drip": "drop", "bile_splash": "drop", "spore_puff": "puff", "spore_haze": "puff", "nerve_spark": "spark",
    "nerve_pulse": "spark", "core_glow": "glow", "blood_burst": "drop", "flesh_chunks": "chunk", "root_dust": "puff",
    "laser_charge": "spark", "laser_beam": "glow", "eye_glint": "glow", "mucus_string": "string",
}


def sprite(family, frame, size=16):
    y, x = np.mgrid[0:size, 0:size]
    c = (size - 1) / 2
    r = np.hypot(x - c, y - c)
    a = np.zeros((size, size))
    rng = np.random.default_rng(frame * 31 + hash(family) % 997)
    if family == "puff":
        rad = 3 + frame * 1.4
        a = np.clip(1 - r / rad, 0, 1) ** 0.6
        a *= 0.6 + 0.4 * rng.random((size, size))
    elif family == "drop":
        rr = np.hypot((x - c) * 1.0, (y - c - 1) * 0.8)
        a = (rr < 3.5 - frame * 0.6).astype(float)
    elif family == "spark":
        a = np.clip(1 - np.minimum(np.abs(x - c), np.abs(y - c)) / 1.2, 0, 1) * np.clip(1 - r / (6 - frame), 0, 1)
    elif family == "glow":
        a = np.clip(1 - r / (7 - frame), 0, 1) ** 1.5
    elif family == "chunk":
        a = ((np.abs(x - c) < 3 - frame * 0.5) & (np.abs(y - c) < 2.5)).astype(float)
        a *= 0.8 + 0.2 * rng.random((size, size))
    elif family == "string":
        a = ((np.abs(x - c) < 0.8) & (np.abs(y - c) < 7 - frame)).astype(float)
    img = np.zeros((size, size, 4), np.uint8)
    shade = 0.75 + 0.25 * (1 - np.clip(r / c, 0, 1))
    img[..., :3] = (255 * shade[..., None]).astype(np.uint8)  # white; tinted in code
    img[..., 3] = (np.clip(a, 0, 1) * 255).astype(np.uint8)
    return Image.fromarray(img, "RGBA")


def particles():
    tdir = mk(ASSETS, "textures", "particle")
    pdir = mk(ASSETS, "particles")
    frames = {"puff": 4, "drop": 3, "spark": 3, "glow": 3, "chunk": 2, "string": 3}
    for fam, n in frames.items():
        for i in range(n):
            sprite(fam, i).save(os.path.join(tdir, f"{fam}_{i}.png"))
    for name, fam in PARTICLES.items():
        with open(os.path.join(pdir, f"{name}.json"), "w") as f:
            json.dump({"textures": [f"{NS}:{fam}_{i}" for i in range(frames[fam])]}, f, indent=2)


# ---------------- blocks & items ----------------
def tile16(mat, seed=0, glow=False):
    atlas, glowmap = texture.build(seed=7)
    ox, oy = texture.tile_origin(mat)
    rng = np.random.default_rng(seed)
    dx, dy = rng.integers(0, 48, 2)
    im = atlas.crop((ox + dx, oy + dy, ox + dx + 16, oy + dy + 16))
    return im


BLOCKS = {  # id -> (material, extra)
    "flesh": ("flesh", {}), "hardened_flesh": ("flesh_dark", {}), "flesh_membrane": ("mucus", {}),
    "glow_vein": ("glow_vein", {"light": True}), "heart_core": ("core", {"light": True}), "rib_bone": ("bone", {}),
    "syringe_cache": ("chitin", {}), "ruptured_vent": ("spore", {}),
}


def blocks_and_items():
    bt = mk(ASSETS, "textures", "block", BOSS)
    it = mk(ASSETS, "textures", "item", BOSS)
    for i, (bid, (mat, extra)) in enumerate(BLOCKS.items()):
        im = tile16(mat, i)
        if bid == "syringe_cache":
            a = np.array(im)
            a[3:13, 7:9, :3] = [220, 240, 250]
            a[5:11, 7:9, :3] = [150, 200, 40]
            a[2, 6:10, :3] = [200, 200, 200]
            im = Image.fromarray(a)
        if bid == "ruptured_vent":
            a = np.array(im)
            yy, xx = np.mgrid[0:16, 0:16]
            a[np.hypot(xx - 7.5, yy - 7.5) < 4] = [20, 6, 10, 255]
            im = Image.fromarray(a)
        im.save(os.path.join(bt, f"{bid}.png"))
    # syringe item: glass barrel, green purgative, steel needle
    a = np.zeros((16, 16, 4), np.uint8)
    for k in range(9):
        x, y = 3 + k, 12 - k
        a[y, x] = [200, 225, 235, 255]
        a[y - 1, x] = [200, 225, 235, 255]
        if 1 <= k <= 6:
            a[y, x] = [150, 205, 40, 255]
    for k in range(3):
        a[3 - k, 12 + k] = [170, 170, 180, 255]
    a[13, 2] = a[13, 3] = a[12, 2] = [90, 90, 100, 255]
    a[14, 1] = [90, 90, 100, 255]
    Image.fromarray(a).save(os.path.join(it, "purgative_syringe.png"))
    # calyx heart trophy
    im = tile16("core", 3).resize((16, 16))
    a = np.array(im)
    yy, xx = np.mgrid[0:16, 0:16]
    mask = np.hypot((xx - 7.5) * 0.9, (yy - 8.5)) < 6.5
    a[~mask, 3] = 0
    a[mask & (np.hypot(xx - 7.5, yy - 8) < 2.5)] = [255, 220, 120, 255]
    Image.fromarray(a).save(os.path.join(it, "calyx_heart.png"))


# ---------------- sounds ----------------
def sound_files(ids, synth=True):
    """OGGs go to sounds/<boss>/; sounds.json is shared by all bosses, so only this boss's keys are replaced."""
    sdir = mk(ASSETS, "sounds", BOSS)
    path = os.path.join(ASSETS, "sounds.json")
    j = json.load(open(path)) if os.path.exists(path) else {}
    j = {k: v for k, v in j.items() if not k.startswith(BOSS + ".")}
    for sid in ids:
        fname = sid.replace(".", "_")
        if synth:
            sounds.write(sid, os.path.join(sdir, f"{fname}.ogg"))
        entry = {"subtitle": f"subtitles.{NS}.{BOSS}.{sid}", "sounds": [{"name": f"{NS}:{BOSS}/{fname}"}]}
        if sid.startswith(("bloom.", "encounter.", "attack.", "ambient.")):
            entry["sounds"][0]["attenuation_distance"] = 256
        if sid == "ambient.stomach" or sid == "bloom.laser_loop":
            entry["sounds"][0]["stream"] = True
        j[f"{BOSS}.{sid}"] = entry
    with open(path, "w") as f:
        json.dump(dict(sorted(j.items())), f, indent=2)
    with open(SOUND_IDS, "w") as f:
        f.write("\n".join(ids))
    return ids


def sound_ids_java(ids):
    body = ",\n            ".join(f'"{s}"' for s in ids)
    src = f"""package net.teamaof.skylorebosses.bosses.matriscalyx;

/** GENERATED by bosses/matris_calyx/tools/export_to_mod.py: Matris sound ids (registered as skylore_bosses:matris_calyx.<id>). */
public final class MatrisSoundIds {{
    public static final String[] ALL = {{
            {body}
    }};

    private MatrisSoundIds() {{}}
}}
"""
    with open(os.path.join(mk(JAVA), "MatrisSoundIds.java"), "w") as f:
        f.write(src)


if __name__ == "__main__":
    copy_models()
    ids = locators_java()
    particles()
    blocks_and_items()
    sound_files(ids, synth="--no-sounds" not in sys.argv)
    sound_ids_java(ids)
    print(len(ids), "sounds;", len(ENTITY_MODELS) + len(BLOCK_MODELS), "models exported")
