package net.teamaof.skylorebosses.bosses.overhead;

/** GENERATED by bosses/overhead/tools/export_to_mod.py: Overhead sound ids (registered as skylore_bosses:overhead.<id>). */
public final class OverheadSoundIds {
    public static final String[] ALL = {
            "brownout",
            "carpet.impact",
            "carpet.klaxon",
            "death",
            "flak.burst",
            "flak.fire",
            "flare.burst",
            "flare.launch",
            "howitzer.fire",
            "howitzer.load",
            "hurt",
            "laser.charge",
            "laser.loop",
            "laser.vent",
            "lockdown.gate",
            "missile.impact",
            "missile.launch",
            "missile.lock",
            "missile.open",
            "overcharge.charge",
            "overcharge.discharge",
            "power.charge",
            "power.pulse",
            "pylon.break",
            "pylon.hit",
            "pylon.hum",
            "pylon.online",
            "pylon.rebuild",
            "rearm.siren",
            "rotor.loop",
            "shell.impact",
            "shield.deflect",
            "shield.pulse",
            "strafe.fire",
            "strafe.spinup",
            "victory"
    };

    private OverheadSoundIds() {}
}
