package net.teamaof.skylorebosses.bosses.overhead;

import java.util.Map;
import net.teamaof.skylorebosses.core.fx.ModelLocators;

/** GENERATED by bosses/overhead/tools/export_to_mod.py from the Blockbench specs. Rest-pose locators in model pixels. */
public final class OverheadLocators {
    private OverheadLocators() {}

    public static void register() {
        ModelLocators.register("overhead", Map.ofEntries(Map.entry("core", new float[]{0.00f, 30.00f, 0.00f}), Map.entry("lens", new float[]{0.00f, 24.00f, -38.00f}), Map.entry("beacon", new float[]{8.00f, 55.00f, 14.00f}), Map.entry("flare", new float[]{-9.00f, 46.00f, 9.00f}), Map.entry("thruster_0", new float[]{-30.00f, 23.00f, -22.00f}), Map.entry("thruster_1", new float[]{30.00f, 23.00f, -22.00f}), Map.entry("thruster_2", new float[]{-30.00f, 23.00f, 22.00f}), Map.entry("thruster_3", new float[]{30.00f, 23.00f, 22.00f}), Map.entry("bay_l", new float[]{-26.00f, 27.00f, -4.00f}), Map.entry("bay_r", new float[]{26.00f, 27.00f, -4.00f}), Map.entry("muzzle", new float[]{0.00f, 13.00f, -37.00f}), Map.entry("gatling", new float[]{0.00f, 16.00f, -39.00f})));
        ModelLocators.register("howitzer_shell", Map.ofEntries(Map.entry("trail", new float[]{0.00f, 4.00f, 6.00f})));
        ModelLocators.register("seeker_missile", Map.ofEntries(Map.entry("exhaust", new float[]{0.00f, 3.00f, 7.50f})));
        ModelLocators.register("generator_pylon", Map.ofEntries(Map.entry("core", new float[]{0.00f, 67.00f, 0.00f}), Map.entry("top", new float[]{0.00f, 80.00f, 0.00f}), Map.entry("pad", new float[]{0.00f, 12.00f, 0.00f})));
    }
}
